### ISSUE TITLE
Add a contribution guide

### ISSUE THREAD

**Issue by AblingerOscar** [uptake/autofocus#119]
It seems like I can't find a proper contribution guide. Since this project clearly wants contributions looking at the `good first issue` and `Hacktoberfest` tags from the issues, this seems like something that should be added.

Or is there one and I just can't find it? :P

**Comment by gsganden** [comment]
Correct, it does not have one, and it should.

**Comment by Manusreekumar** [comment]
I can see a pull_request_template.md in .github folder, that outlines the steps to be completed for creating a PR. Community guidelines for contribution is present in conduct.md as well. Is there any other expectations out of a contribution guide other than the ones above ?

**Comment by gsganden** [comment]
Yes, at one point there was an issue to create either a pull_request_template.md or a contributing.md, and I choose to create a pull_request_template.md. That might be sufficient with a little development. I prefer having all of the instructions in one place if feasible. At the least pull_request_template.md should ask contributors to make PRs into a dev branch that I need to create.

**Comment by AblingerOscar** [comment]
> Is there any other expectations out of a contribution guide other than the ones above?

There is less so an expectation of what should be inside it, but moreso an expectation of it existing.
Even if it just references already existing files, before even thinking about contributing, the CONTRIBUTING file is the first place to look how well maintained the project is. It not existing is a major red flag by an Open Source project for me.

The file should usually have:
- Explanation of what kind of contributions are welcome/sought out and whether & where to notify somebody about it being worked on
- How to contribute (usually a link to one of the many guides is enough, unless you have specific additional rules for your project like merging into the dev branch; I like the [github guide](https://guides.github.com/activities/forking/) for it)
- Different conventions for code, PRs, issues, commits etc.
- Lastly, if you want to really help contributors, an explanation of the current architecture. This can be a bit more work, but it can pay off by making it a lot easier to contribute.

[See The Documentation Compendium](https://github.com/kylelobo/The-Documentation-Compendium/blob/master/en/CONTRIBUTING.md)

In the end, it's more important to show that you support contributors than having the perfect guide, so take this more as a suggestion for a contribution guide and not the definite answer. Your PR-template already has a lot of what is expected of a contribution guide. But you only really see it when you've already made your contribution and only want to submit it.

**Comment by AblingerOscar** [comment]
Since the PR is merged, should this be closed? Or is there more you want to add?

**Comment by gsganden** [comment]
I think we can close it. Thanks!
