### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by gsganden** [uptake/autofocus#25]

**Comment by jayqi** [comment]
I started on this. Picked pytest since that AFAIK that seems to be the popular choice.

**Comment by gsganden** [comment]
We have a couple basic end-to-end tests for the prediction service now. I'm sure we could use more tests around edge cases and perhaps some unit tests of individual components.

**Comment by gsganden** [comment]
#103 got us started. I'm going to close this issue because it's too broad to be useful. Additional issues about specific testing needs could be valuable.

**Comment by jameslamb** [comment]
> "it's too broad to be useful"

@gsganden would you consider issues with targets like "get unit test coverage to x% coverage" in increments of 10 or 20? That was useful for me on `doppel-cli` and had less mental effort for me (as a maintainer) that coming up with issues like "add unit tests confirming that thing ABC works".

If you pair these types of issues with requiring that coverage is above a floor in CI, it can gradually build up the quality of the project.

**Comment by gsganden** [comment]
I would not encourage anyone to spend their time writing tests for Autofocus at this time. I don't see any significant risks that tests would help mitigate. Autofocus isn't a library; it's an open machine learning project with a very simple app for serving predictions.

The app has tests to make sure that the inputs and outputs have the right form. I don't see what else you would test in an end-to-end manner, and I don't think it's worthwhile to write smaller unit tests both because it doesn't really matter as long as the end-to-end tests work and because I want to rewrite the app from scratch before I do further development on it. Moreover, we have one user right now. If he hits a bug, he will file an issue, and I will write a test and then fix it. More speculative testing would not be productive given our current situation.

The model is trained by calling pandas and fastai methods. The things to test are just whether the model runs in the app, which is covered, and how well it performs in practice, which Mason is working on and isn't a unit test.

The scripts that created the current main dataset basically only need to have been run once. We still have them just in case, but no one is depending on them. There are a few functions in https://github.com/uptake/autofocus/blob/master/autofocus/build_dataset/helpers.py that we could want to reuse elsewhere where tests make some sense, but there is so little risk associated with them currently that writing tests for them would not be a good use of time.
