### ISSUE TITLE
add CODEOWNERS file

### ISSUE THREAD

**Issue by jameslamb** [uptake/autofocus#91]
I learned about [this cool thing](https://help.github.com/en/articles/about-code-owners) over in `fRanz`. GitHub allows you to add a `CODEOWNERS` file that will be used to set default reviewers when PRs are opened.

This has to be done by a repo admin, so assigning to you @gsganden

**Comment by gsganden** [comment]
Cool! Do you see a use for it in this project currently?

**Comment by jameslamb** [comment]
Yes I think so. Even if you just do

```
*   @gsganden 
```

It would add you as the reviewer automatically on all PRs. Right now, if someone who isn't me or you submits a PR, they do not have the power to request a review from you and have to wait for you to come do it (so just saves you a click).

I've also noticed that _by convention_ you add me as a reviewer on stuff related to misc. maintenance stuff like CI or things in the `.github/` directory. You could change that convention to automation by adding lines like this if you'd like:

```
.travis.yml    @jameslamb 
.github/*   @jameslamb   
```

Up to you!
